#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "wookie/lexer"
  require "wookie/nodes"

class WookieParser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 92)
  def parse(code, show_tokens=false)
    @tokens = ::WookieLexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    -1,     5,    20,    19,     5,    13,    14,    15,    16,    17,
    18,    25,    26,    23,    24,     6,    45,    46,     6,    20,
    19,     5,    13,    14,    15,    16,    17,    18,     5,    37,
    25,    26,    23,    24,    30,     6,    44,    39,    25,    26,
    20,    19,     6,    13,    14,    15,    16,    17,    18,    25,
    26,   -20,   -20,   -20,   -20,    20,    19,    27,    13,    14,
    15,    16,    17,    18,    20,    19,    43,    13,    14,    15,
    16,    17,    18,    20,    19,    21,    13,    14,    15,    16,
    17,    18,    20,    19,    28,    13,    14,    15,    16,    17,
    18,    20,    19,    37,    13,    14,    15,    16,    17,    18,
    20,    19,    48,    13,    14,    15,    16,    17,    18,    37,
   nil,    25,    26,    23,    24,    25,    26,    23,    24 ]

racc_action_check = [
     0,     2,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    36,    36,    36,    36,     2,    42,    42,     0,    37,
    37,    37,    37,    37,    37,    37,    37,    37,    41,    28,
     3,     3,     3,     3,    21,    37,    41,    28,    32,    32,
    22,    22,    41,    22,    22,    22,    22,    22,    22,    33,
    33,    22,    22,    22,    22,    25,    25,    18,    25,    25,
    25,    25,    25,    25,    20,    20,    39,    20,    20,    20,
    20,    20,    20,    26,    26,     1,    26,    26,    26,    26,
    26,    26,    23,    23,    19,    23,    23,    23,    23,    23,
    23,    24,    24,    45,    24,    24,    24,    24,    24,    24,
    27,    27,    46,    27,    27,    27,    27,    27,    27,    29,
   nil,    29,    29,    29,    29,    31,    31,    31,    31 ]

racc_action_pointer = [
     0,    75,    -3,    17,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40,    74,
    62,    34,    38,    80,    89,    53,    71,    98,    18,    98,
   nil,   102,    25,    36,   nil,   nil,    -2,    17,   nil,    56,
   nil,    24,    -4,   nil,   nil,    82,    92,   nil,   nil ]

racc_action_default = [
   -20,   -34,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -25,   -34,
   -20,   -34,    -5,   -20,   -20,   -20,   -20,   -20,   -34,   -34,
    49,    -4,   -21,   -22,   -23,   -24,   -26,   -20,   -28,   -30,
   -33,   -34,   -34,   -31,   -27,   -34,   -34,   -29,   -32 ]

racc_goto_table = [
    22,     2,    38,    40,    29,     1,    31,    32,    33,    34,
    35,    36,    42,   nil,   nil,   nil,   nil,   nil,   nil,    47,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,    22 ]

racc_goto_check = [
     4,     2,    11,    11,     3,     1,     3,     3,     3,     3,
     3,     3,    12,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,     4 ]

racc_goto_pointer = [
   nil,     5,     1,   -16,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   -26,   -27 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     7,     8,     9,    10,    11,
    12,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 23, :_reduce_1,
  1, 23, :_reduce_2,
  1, 24, :_reduce_3,
  3, 24, :_reduce_4,
  2, 24, :_reduce_5,
  1, 24, :_reduce_6,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 27, :_reduce_15,
  1, 27, :_reduce_16,
  1, 27, :_reduce_17,
  1, 27, :_reduce_18,
  1, 27, :_reduce_19,
  0, 28, :_reduce_none,
  3, 28, :_reduce_21,
  3, 28, :_reduce_22,
  3, 28, :_reduce_23,
  3, 28, :_reduce_24,
  1, 29, :_reduce_25,
  3, 30, :_reduce_26,
  3, 33, :_reduce_27,
  3, 31, :_reduce_28,
  6, 31, :_reduce_29,
  0, 34, :_reduce_30,
  1, 34, :_reduce_31,
  3, 34, :_reduce_32,
  3, 32, :_reduce_33 ]

racc_reduce_n = 34

racc_shift_n = 49

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :DEF => 3,
  :NEWLINE => 4,
  :NUMBER => 5,
  :STRING => 6,
  :TRUE => 7,
  :FALSE => 8,
  :NIL => 9,
  :IDENTIFIER => 10,
  :INDENT => 11,
  :DEDENT => 12,
  "*" => 13,
  "/" => 14,
  "+" => 15,
  "-" => 16,
  "=" => 17,
  ";" => 18,
  "(" => 19,
  ")" => 20,
  "," => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "DEF",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "INDENT",
  "DEDENT",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"=\"",
  "\";\"",
  "\"(\"",
  "\")\"",
  "\",\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Operator",
  "GetLocal",
  "SetLocal",
  "Def",
  "If",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 19)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 20)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 25)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 26)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 27)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'grammar.y', 45)
  def _reduce_15(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_16(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 47)
  def _reduce_17(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 48)
  def _reduce_18(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_19(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'grammar.y', 53)
  def _reduce_21(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 54)
  def _reduce_22(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_23(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 56)
  def _reduce_24(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 60)
  def _reduce_25(val, _values, result)
     result = GetLocalNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 64)
  def _reduce_26(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 67)
  def _reduce_27(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 71)
  def _reduce_28(val, _values, result)
     result = DefNode.new(val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 73)
  def _reduce_29(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 77)
  def _reduce_30(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 78)
  def _reduce_31(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_32(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_33(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class WookieParser
