#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "wookie/lexer"
  require "wookie/nodes"

class WookieParser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 68)
  def parse(code, show_tokens=false)
    @tokens = ::WookieLexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    -1,    17,     5,    11,    12,    13,    14,    15,    16,    23,
     5,    21,    22,    -5,     6,    -5,    11,    12,    13,    14,
    15,    16,     6,    21,    22,    19,    20,    -5,    11,    12,
    13,    14,    15,    16,    11,    12,    13,    14,    15,    16,
    11,    12,    13,    14,    15,    16,    11,    12,    13,    14,
    15,    16,    11,    12,    13,    14,    15,    16,    21,    22,
    19,    20,    21,    22,    19,    20,    21,    22,    24 ]

racc_action_check = [
     0,     1,     0,     0,     0,     0,     0,     0,     0,    16,
     2,    26,    26,    18,     0,    18,    18,    18,    18,    18,
    18,    18,     2,    30,    30,    30,    30,    18,    21,    21,
    21,    21,    21,    21,    23,    23,    23,    23,    23,    23,
    19,    19,    19,    19,    19,    19,    22,    22,    22,    22,
    22,    22,    20,    20,    20,    20,    20,    20,     3,     3,
     3,     3,    25,    25,    25,    25,    27,    27,    17 ]

racc_action_pointer = [
     0,     1,     8,    49,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    -4,    68,    13,    37,
    49,    25,    43,    31,   nil,    53,     2,    57,   nil,   nil,
    14 ]

racc_action_default = [
   -18,   -25,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -23,   -25,   -18,   -18,
   -18,   -18,   -18,   -18,    31,    -4,   -19,   -20,   -21,   -22,
   -24 ]

racc_goto_table = [
     3,     4,     2,    18,     1,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    25,    26,
    27,    28,    29,    30 ]

racc_goto_check = [
     3,     4,     2,     4,     1,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,     3,
     3,     3,     3,     3 ]

racc_goto_pointer = [
   nil,     4,     2,     0,     1,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     7,     8,     9,    10 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 16, :_reduce_1,
  1, 16, :_reduce_2,
  1, 17, :_reduce_3,
  3, 17, :_reduce_4,
  2, 17, :_reduce_5,
  1, 17, :_reduce_6,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 18, :_reduce_none,
  1, 18, :_reduce_none,
  1, 18, :_reduce_none,
  1, 18, :_reduce_none,
  1, 20, :_reduce_13,
  1, 20, :_reduce_14,
  1, 20, :_reduce_15,
  1, 20, :_reduce_16,
  1, 20, :_reduce_17,
  0, 21, :_reduce_none,
  3, 21, :_reduce_19,
  3, 21, :_reduce_20,
  3, 21, :_reduce_21,
  3, 21, :_reduce_22,
  1, 22, :_reduce_23,
  3, 23, :_reduce_24 ]

racc_reduce_n = 25

racc_shift_n = 31

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :NUMBER => 3,
  :STRING => 4,
  :TRUE => 5,
  :FALSE => 6,
  :NIL => 7,
  :IDENTIFIER => 8,
  "*" => 9,
  "/" => 10,
  "+" => 11,
  "-" => 12,
  "=" => 13,
  ";" => 14 }

racc_nt_base = 15

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"=\"",
  "\";\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Operator",
  "GetLocal",
  "SetLocal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 16)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 17)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 21)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 22)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 23)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'grammar.y', 40)
  def _reduce_13(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 41)
  def _reduce_14(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 42)
  def _reduce_15(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 43)
  def _reduce_16(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 44)
  def _reduce_17(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

# reduce 18 omitted

module_eval(<<'.,.,', 'grammar.y', 48)
  def _reduce_19(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_20(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 50)
  def _reduce_21(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_22(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_23(val, _values, result)
     result = GetLocalNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 59)
  def _reduce_24(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class WookieParser
